# mysql.database.yml

#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html


## MySQL2
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("ENV_MAX_THREADS") { 5 } %>
  username: <%= ENV["USERNAME_KEY"] %>
  password: <%= ENV["PASSWORD_KEY"] %>

development:
  adapter: mysql2
  encoding: utf8
  database: rc09_sinatra_crm_assessment
  pool: 5
  username: root
  password: Palo5non!

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: test_rc09_sinatra_crm_assessment
  pool: 5
  username: root
  password: Palo5non!

production:
  <<: *default
  database: rc09_sinatra_crm_assessment

