## MySQL2
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("ENV_MAX_THREADS") { 5 } %>
  database: <%= ENV["DATABASE_KEY"] %>
  username: <%= ENV["USERNAME_KEY"] %>
  password: <%= ENV["PASSWORD_KEY"] %>

development:
  <<: *default

test:
  <<: *default


production:
  <<: *default

