## MySQL2
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("ENV_MAX_THREADS") { 5 } %>
  username: <%= ENV["USERNAME_KEY"] %>
  password: <%= ENV["PASSWORD_KEY"] %>

development:
  <<: *default
  database: twenty45_development

test:
  <<: *default
  database: test_twenty45_development

production:
  <<: *default
  database: sch_twenty45_development mydb
